[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npx serve ."
  targetPort = 3000
  port = 8888

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
